import type { WindPlantEstimate } from "@/types/climagrid";

export const DEMO_SNAPSHOT_DATE = "2026-08-31";

export const demoPlantEstimates: WindPlantEstimate[] = [
  {
    id: "eol-ba-001",
    onsId: "EOL.CVBA.001",
    name: "Complexo Caetité I",
    state: "BA",
    latitude: -14.07,
    longitude: -42.49,
    installedCapacityMw: 180,
    estimatedGenerationMw: 142.6,
    confidenceLowMw: 128.2,
    confidenceHighMw: 157.1,
    confidencePercent: 90,
    historicalAvailabilityPercent: 94.1,
    historicalCurtailmentPercent: 18.4,
    probableReason: "ENE",
    riskLevel: "high",
  },
  {
    id: "eol-ba-002",
    onsId: "EOL.MCBA.014",
    name: "Morro do Chapéu Sul",
    state: "BA",
    latitude: -11.55,
    longitude: -41.16,
    installedCapacityMw: 150,
    estimatedGenerationMw: 103.8,
    confidenceLowMw: 91.4,
    confidenceHighMw: 116.2,
    confidencePercent: 90,
    historicalAvailabilityPercent: 91.8,
    historicalCurtailmentPercent: 11.2,
    probableReason: "CNF",
    riskLevel: "medium",
  },
  {
    id: "eol-ce-001",
    onsId: "EOL.TRCE.007",
    name: "Trairi Eólica",
    state: "CE",
    latitude: -3.27,
    longitude: -39.27,
    installedCapacityMw: 90,
    estimatedGenerationMw: 61.3,
    confidenceLowMw: 54.7,
    confidenceHighMw: 67.9,
    confidencePercent: 90,
    historicalAvailabilityPercent: 96.2,
    historicalCurtailmentPercent: 5.9,
    probableReason: "NONE",
    riskLevel: "low",
  },
  {
    id: "eol-pe-001",
    onsId: "EOL.ARPE.003",
    name: "Araripe III",
    state: "PE",
    latitude: -7.61,
    longitude: -40.41,
    installedCapacityMw: 210,
    estimatedGenerationMw: 176.9,
    confidenceLowMw: 159.5,
    confidenceHighMw: 194.3,
    confidencePercent: 90,
    historicalAvailabilityPercent: 93.6,
    historicalCurtailmentPercent: 14.7,
    probableReason: "ENE",
    riskLevel: "high",
  },
  {
    id: "eol-pi-001",
    onsId: "EOL.LVPI.005",
    name: "Lagoa dos Ventos II",
    state: "PI",
    latitude: -8.17,
    longitude: -42.2,
    installedCapacityMw: 230,
    estimatedGenerationMw: 169.4,
    confidenceLowMw: 151.8,
    confidenceHighMw: 187,
    confidencePercent: 90,
    historicalAvailabilityPercent: 92.9,
    historicalCurtailmentPercent: 9.6,
    probableReason: "REL",
    riskLevel: "medium",
  },
  {
    id: "eol-rn-001",
    onsId: "EOL.SBRN.009",
    name: "Serra Branca IX",
    state: "RN",
    latitude: -5.12,
    longitude: -36.31,
    installedCapacityMw: 140,
    estimatedGenerationMw: 118.7,
    confidenceLowMw: 107.3,
    confidenceHighMw: 130.1,
    confidencePercent: 90,
    historicalAvailabilityPercent: 95.4,
    historicalCurtailmentPercent: 7.3,
    probableReason: "CNF",
    riskLevel: "medium",
  },
  {
    id: "eol-rn-002",
    onsId: "EOL.MIRN.004",
    name: "Miassaba III",
    state: "RN",
    latitude: -5.04,
    longitude: -36.42,
    installedCapacityMw: 65,
    estimatedGenerationMw: 42.1,
    confidenceLowMw: 36.8,
    confidenceHighMw: 47.4,
    confidencePercent: 90,
    historicalAvailabilityPercent: 90.7,
    historicalCurtailmentPercent: 4.2,
    probableReason: "NONE",
    riskLevel: "low",
  },
  {
    id: "eol-ba-003",
    onsId: "EOL.GOBA.002",
    name: "Gentio do Ouro II",
    state: "BA",
    latitude: -11.43,
    longitude: -42.51,
    installedCapacityMw: 120,
    estimatedGenerationMw: 88.5,
    confidenceLowMw: 76.9,
    confidenceHighMw: 100.1,
    confidencePercent: 90,
    historicalAvailabilityPercent: 89.8,
    historicalCurtailmentPercent: 16.1,
    probableReason: "PAR",
    riskLevel: "high",
  },
];
