import type { WindPlantEstimate } from "@/types/climagrid";

export const DEMO_SNAPSHOT_DATE = "2024-01-31";

export const demoPlantEstimates: WindPlantEstimate[] = [
  {
    id: "CJU_BACAE",
    onsId: "CJU_BACAE",
    name: "Conjunto Eólico Caetité 123",
    state: "BA",
    latitude: -14.07,
    longitude: -42.49,
    installedCapacityMw: 180,
    observedGenerationMw: 142.6,
    estimatedGenerationMw: null,
    capacityFactorPercent: 79.2,
    u100: 7.1,
    v100: -3.2,
    windSpeedMps: 7.79,
    windDirectionDegrees: 294.3,
    generationSource: "ONS_GERACAO_USINA_2_HO",
    weatherSource: "ERA5",
    suggestedBusAllocations: [{ busNumber: "81501", busName: "EOL CAETITE", allocationFactor: 1, allocatedGenerationMw: 142.6 }],
    mappingCoveragePercent: 100,
  },
  {
    id: "CJU_CEITR",
    onsId: "CJU_CEITR",
    name: "Conjunto Eólico Trairi",
    state: "CE",
    latitude: -3.27,
    longitude: -39.27,
    installedCapacityMw: 90,
    observedGenerationMw: 61.3,
    estimatedGenerationMw: null,
    capacityFactorPercent: 68.1,
    u100: 6.5,
    v100: -2.1,
    windSpeedMps: 6.83,
    windDirectionDegrees: 287.9,
    generationSource: "ONS_GERACAO_USINA_2_HO",
    weatherSource: "ERA5",
    suggestedBusAllocations: [{ busNumber: "80742", busName: "EOL TRAIRI", allocationFactor: 1, allocatedGenerationMw: 61.3 }],
    mappingCoveragePercent: 100,
  },
  {
    id: "CJU_RNSRB",
    onsId: "CJU_RNSRB",
    name: "Conjunto Eólico Serra Branca",
    state: "RN",
    latitude: -5.12,
    longitude: -36.31,
    installedCapacityMw: 140,
    observedGenerationMw: 118.7,
    estimatedGenerationMw: null,
    capacityFactorPercent: 84.8,
    u100: 8.4,
    v100: -1.7,
    windSpeedMps: 8.57,
    windDirectionDegrees: 281.4,
    generationSource: "ONS_GERACAO_USINA_2_HO",
    weatherSource: "ERA5",
    suggestedBusAllocations: [{ busNumber: "81351", busName: "EOL SERRA BRANCA", allocationFactor: 1, allocatedGenerationMw: 118.7 }],
    mappingCoveragePercent: 100,
  },
  {
    id: "CJU_PILVV",
    onsId: "CJU_PILVV",
    name: "Conjunto Eólico Lagoa dos Ventos",
    state: "PI",
    latitude: -8.17,
    longitude: -42.2,
    installedCapacityMw: 230,
    observedGenerationMw: 169.4,
    estimatedGenerationMw: null,
    capacityFactorPercent: 73.7,
    u100: 7.8,
    v100: -2.8,
    windSpeedMps: 8.29,
    windDirectionDegrees: 289.7,
    generationSource: "ONS_GERACAO_USINA_2_HO",
    weatherSource: "ERA5",
    suggestedBusAllocations: [{ busNumber: "80491", busName: "EOL LAGOA VENTOS", allocationFactor: 1, allocatedGenerationMw: 169.4 }],
    mappingCoveragePercent: 100,
  },
];
